name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: realcommang
      - name: Commit & Push
        run: |
          git config user.name "realcommang"
          git config user.email "katlelo@naver.com"
          git add -A .
          git commit -m "generated"
          git push https://realcommang:${{ secrets.TOKEN }}@github.com/realcommang/realcommang.git
